#----------------------------------------------------------------
# Title: berryhill-composers.yaml
# Author: Nolan Berryhill
# Date: 08/26/23
# Description: YAML file for describing composer API operations
#----------------------------------------------------------------

#Set Open API version of 3.0.0
openapi: 3.0.0
#Title and version of API
info:
  title: Composer API
  version: 1.0.0

paths:
#Describe the findAllComposers GET operations and responses
  /composers:
    get:
      tags:
        - Composers
      summary: Retrieve all composers
      operationId: findAllComposers
      responses:
        '200':
          description: Successful response
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    post:
      tags:
        - Composers
      summary: Create a new composer
      operationId: createComposer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: Successful response
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

  #Describe the findComposerById GET operations and responses
  /composers/{id}:
    get:
      tags:
        - Composers
      summary: Retrieve a composer by ID
      operationId: findComposerById
      parameters:
        - name: id
          in: path
          description: ID of the composer to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception


